### PR TITLE
Convertir fin de línea a LF para Windows

### PR DESCRIPTION
**Pull request by DennisDyallo**
Hay que ver si funciona en Linux, no es posible para mi ahora. Pero con esta aumentación, se funciona en Windows 10

### CODE REVIEW

**Comment by DennisDyallo** [comment]
Ah well, that only got me passed the Docker Up. 

When I load up the Frontend and click login (which creds?) I get a "No connection with SoulSync API" error. Am I missing some configuration?

**Comment by xaviqo** [comment]
I have to test it on my system. The truth is that I have developed it on Linux and I have not thought about the difference of the LF. 

Thank you very much for your help!

The default creds are admin/admin. 

Is it possible that you are getting a connection error with the API because you are entering from https instead of http?

I will try to finish the documentation this week!

**Comment by DennisDyallo** [comment]
> I have to test it on my system. The truth is that I have developed it on Linux and I have not thought about the difference of the LF.
> 
> Thank you very much for your help!
> 
> The default creds are admin/admin.
> 
> Is it possible that you are getting a connection error with the API because you are entering from https instead of http?
> 
> I will try to finish the documentation this week!

Alright, I will try the credentials and using http:// instead in the Vue app :) 
This seems like a really cool and useful project. I'm a DJ as well so this would help immensely

**Comment by xaviqo** [comment]
I am also a dj and soulseek user and that's why I created this project.  Tyvm! :)

**Comment by xaviqo** [comment]
Tested on Linux and it works

**Comment by DennisDyallo** [comment]
Alright! I'll come back here every once in a while to see the docs updated. Atm I don't have time to guess how to set everything up :) Thanks for your work! @xaviqo

**Pull request merged**
